# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

sudo: required
go:
  - "1.10.x"

services:
  - docker

matrix:
  include:
    - os: linux
      language: python
      python: 3.4
      env:
        - TOXENV=py34
        - PYTHON=3.4
    - os: linux
      language: python
      python: 3.5
      env:
        - TOXENV=py35
        - PYTHON=3.5
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON=3.6
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python3.6]

before_install:
    # Setup environment variables
    - export LIBSKYCOIN="0.24.1"
    - export LIBSKYCOIN_URL="https://transfer.sh/Pxwom/libskycoin-linux-x86_64.so"

install:
    - sudo pip install tox-travis
    - curl -sL -o exchange_app/libskycoin.so "${LIBSKYCOIN_URL}"
    - mkdir swig_build && cd swig_build && wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz && tar -zxf swig-3.0.12.tar.gz && cd swig-3.0.12 && sudo ./configure --prefix=/usr && sudo make && sudo make install && cd ../../ && sudo rm -rf swig_build

after_failure:
    - cat ./.tox/${TOXENV}/log/${TOXENV}-*.log

script: tox

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
