# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      language: python
      python: 3.4
      env:
        - TOXENV=py34
        - PYTHON=3.4
    - os: linux
      language: python
      python: 3.5
      env:
        - TOXENV=py35
        - PYTHON=3.5
    - os: linux
      language: python
      python: 3.6
      env:
        - TOXENV=py36
        - PYTHON=3.6
      addons:
        apt:
          sources: [deadsnakes]
          packages: [python3.6, python3.6-dev]
    - os: osx
      languague: generic
      env:
        - PYTHON=3.4.8
        - TOXENV=py34
    - os: osx
      languague: generic
      env:
        - PYTHON=3.5.5
        - TOXENV=py35
    - os: osx
      languague: generic
      env:
        - PYTHON=3.6.5
        - TOXENV=py36

before_install:
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-osx.sh; fi
    # Setup environment and PATH in MacOS
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PYCMD_VERSION="$(echo ${PYTHON} | cut -d . -f 1,2)" ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PYCMD_PATH="$(pyenv which python${PYCMD_VERSION})" ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PYCMD_DIRPATH="$( dirname ${PYCMD_PATH} )" ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="${PYCMD_DIRPATH}:/Users/travis/.pyenv/shims:${PATH}" ; fi
    # Print system env info in MacOS
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pyenv versions ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pyenv which python${PYCMD_VERSION} ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then echo "PATH=$PATH" ; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then eval "python${PYCMD_VERSION} --version" ; fi
    # Define command aliases
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then eval "alias python${PYCMD_VERSION}=$(pyenv which python${PYCMD_VERSION})"; fi
    # Setup environment variables
    - export LIBSKY="0.24.1"

install:
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo pip install tox-travis; fi

after_failure:
    - cat ./.tox/${PYTHON}/log/${PYTHON}-*.log

script: tox

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
